# Site settings
title: Allie Sterling
email: sterling.allie@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my site!  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://alliesterling.com" # the base hostname & protocol for your site
twitter_username: allie_sterling
github_username:  ahsterling

# Build settings
markdown: kramdown
